### ISSUE TITLE
Problems with current interface files

### ISSUE THREAD

**Issue by chemistry-sourabh** [CCI-MOC/M2#9]
I opened the interface files in pycharm and it was complaining about inconsistent usage of tabs and spaces. They need to be reformatted.

Auth.py is vague and should be renamed to authorization.py or authentication.py (Note all the lowercase)

Stick to the driver names in the architecture diagram. Like target.py can be renamed to diskless.py or something similar.

Did you guys think about separate ipxe and tftp interfaces ? There might be a better way to package DHCP, PXE and TFTP as a Driver.

**Comment by xuhang57** [comment]
@chemistry-sourabh  Should we close this?

**Comment by chemistry-sourabh** [comment]
Probably you can create a separate issue for the last point regarding PXE and TFTP interfaces and close this ?
